name: Test Build and Push

on:
  push:
    tags:
      - '*.*'
  pull_request:
    tags:
      - '*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get release version
      id: get_version
      run: echo "::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/*/})"

    - uses: actions/checkout@v4
    - name: Build ML Docker image
      run: docker build -t '${{secrets.ORG_NAME}}'/'${{secrets.DOCKER_REPO}}':'${{ steps.get_version.outputs.RELEASE_VERSION  }}' .

    - name: Login to docker
      run: docker login -u '${{secrets.DOCKER_USERNAME}}' -p '${{secrets.DOCKER_PASSWORD}}'

    - name: Push the docker image
      run: docker push '${{secrets.ORG_NAME}}'/'${{secrets.DOCKER_REPO}}':'${{ steps.get_version.outputs.RELEASE_VERSION }}'
