name: ML Docker build push

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build ML Docker image
      run: docker build -t '${{secrets.DOCKER_LOGIN}}'/test-docker:'${{github.sha}}' .
      
    - name: Login to docker
      run: docker login -u '${{secrets.DOCKER_LOGIN}}' -p '${{secrets.DOCKER_PASSWORD}}'

    - name: Push the docker image
      run: docker push '${{secrets.DOCKER_LOGIN}}'/test-docker:'${{github.sha}}'
